# The runner and CMake share one ordered learning path.
file(READ "${PROJECT_SOURCE_DIR}/learning_path.json" LEARNING_PATH)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/learning_path.json")
string(JSON LEVEL_COUNT LENGTH "${LEARNING_PATH}" levels)
math(EXPR LAST_LEVEL "${LEVEL_COUNT} - 1")
foreach(LEVEL RANGE ${LAST_LEVEL})
  string(JSON LESSON_COUNT LENGTH "${LEARNING_PATH}" levels ${LEVEL} exercises)
  math(EXPR LAST_LESSON "${LESSON_COUNT} - 1")
  foreach(LESSON RANGE ${LAST_LESSON})
    string(JSON NAME GET "${LEARNING_PATH}" levels ${LEVEL} exercises ${LESSON} name)
    string(JSON SOURCE GET "${LEARNING_PATH}" levels ${LEVEL} exercises ${LESSON} path)
    if(NOT TARGET ${NAME})
      add_executable(${NAME} "${PROJECT_SOURCE_DIR}/${SOURCE}")
      target_include_directories(${NAME} PRIVATE "${PROJECT_SOURCE_DIR}/tests")
      target_link_libraries(${NAME} PRIVATE Catch2 cplings Threads::Threads)
      get_filename_component(SOURCE_DIRECTORY "${SOURCE}" DIRECTORY)
      set_target_properties(${NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${SOURCE_DIRECTORY}")
      if(CPLINGS_RUN_TESTS_AFTER_BUILD)
        add_custom_command(TARGET ${NAME} POST_BUILD COMMAND ${NAME} COMMENT "Run Tests")
      endif()
    endif()
  endforeach()
endforeach()
